# Generated by Django 5.1.1 on 2024-10-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_color_customer_color_order_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
