# Generated by Django 5.1.1 on 2024-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue')], max_length=7),
        ),
    ]
