# Generated by Django 5.1.1 on 2024-10-05 14:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
