# Generated by Django 5.1.1 on 2024-10-08 13:00

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
