# Generated by Django 5.1.1 on 2024-10-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_login_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.register'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
