# Generated by Django 5.1.1 on 2024-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_login_register_alter_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='register',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
